// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: osmi.proto

package osmi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ TICKETS - ACTUALIZADOS ============
type TicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`          // UUID del evento (requerido)
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"` // UUID del customer (OBLIGATORIO) - ✅ NUEVA BASE DE DATOS
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // UUID del usuario (OPCIONAL) - ✅ NUEVA BASE DE DATOS
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // UUID de la categoría (requerido)
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`                      // Cantidad de tickets (default: 1, max: 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketRequest) Reset() {
	*x = TicketRequest{}
	mi := &file_osmi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRequest) ProtoMessage() {}

func (x *TicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRequest.ProtoReflect.Descriptor instead.
func (*TicketRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{0}
}

func (x *TicketRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *TicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TicketRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *TicketRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type TicketLookup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*TicketLookup_TicketId
	//	*TicketLookup_UserId
	//	*TicketLookup_CustomerId
	//	*TicketLookup_Code
	Lookup        isTicketLookup_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketLookup) Reset() {
	*x = TicketLookup{}
	mi := &file_osmi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketLookup) ProtoMessage() {}

func (x *TicketLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketLookup.ProtoReflect.Descriptor instead.
func (*TicketLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{1}
}

func (x *TicketLookup) GetLookup() isTicketLookup_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *TicketLookup) GetTicketId() string {
	if x != nil {
		if x, ok := x.Lookup.(*TicketLookup_TicketId); ok {
			return x.TicketId
		}
	}
	return ""
}

func (x *TicketLookup) GetUserId() string {
	if x != nil {
		if x, ok := x.Lookup.(*TicketLookup_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *TicketLookup) GetCustomerId() string {
	if x != nil {
		if x, ok := x.Lookup.(*TicketLookup_CustomerId); ok {
			return x.CustomerId
		}
	}
	return ""
}

func (x *TicketLookup) GetCode() string {
	if x != nil {
		if x, ok := x.Lookup.(*TicketLookup_Code); ok {
			return x.Code
		}
	}
	return ""
}

type isTicketLookup_Lookup interface {
	isTicketLookup_Lookup()
}

type TicketLookup_TicketId struct {
	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3,oneof"` // Para GetTicketDetails
}

type TicketLookup_UserId struct {
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof"` // Para ListTickets (usuarios registrados) - ✅ NUEVA ARQUITECTURA
}

type TicketLookup_CustomerId struct {
	CustomerId string `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3,oneof"` // Para ListTickets (clientes invitados) - ✅ NUEVA ARQUITECTURA
}

type TicketLookup_Code struct {
	Code string `protobuf:"bytes,4,opt,name=code,proto3,oneof"` // Para búsqueda por código
}

func (*TicketLookup_TicketId) isTicketLookup_Lookup() {}

func (*TicketLookup_UserId) isTicketLookup_Lookup() {}

func (*TicketLookup_CustomerId) isTicketLookup_Lookup() {}

func (*TicketLookup_Code) isTicketLookup_Lookup() {}

type UpdateTicketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"` // UUID del ticket
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                     // Nuevo estado (available, reserved, sold, used, cancelled, transferred, refunded)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketStatusRequest) Reset() {
	*x = UpdateTicketStatusRequest{}
	mi := &file_osmi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketStatusRequest) ProtoMessage() {}

func (x *UpdateTicketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketStatusRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTicketStatusRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *UpdateTicketStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TicketResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TicketId          string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`                             // UUID público del ticket
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                 // available, reserved, sold, used, cancelled, transferred, refunded
	Code              string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                                                     // Código único del ticket
	QrCodeUrl         string                 `protobuf:"bytes,4,opt,name=qr_code_url,json=qrCodeUrl,proto3" json:"qr_code_url,omitempty"`                        // URL del QR code
	EventName         string                 `protobuf:"bytes,5,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`                          // Nombre del evento
	EventDate         string                 `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`                          // Fecha del evento (Formato RFC3339)
	EventLocation     string                 `protobuf:"bytes,7,opt,name=event_location,json=eventLocation,proto3" json:"event_location,omitempty"`              // Ubicación del evento
	Price             float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`                                                 // Precio del ticket
	CategoryName      string                 `protobuf:"bytes,9,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                 // Nombre de la categoría
	SeatNumber        string                 `protobuf:"bytes,10,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`                      // Número de asiento (opcional)
	CustomerName      string                 `protobuf:"bytes,11,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`                // Nombre del cliente
	CustomerEmail     string                 `protobuf:"bytes,12,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`             // Email del cliente
	CustomerType      string                 `protobuf:"bytes,13,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`                // Tipo de cliente (registered, guest, corporate) - ✅ NUEVO
	UserName          string                 `protobuf:"bytes,14,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                            // Nombre de usuario (si aplica)
	UserRole          string                 `protobuf:"bytes,15,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`                            // Rol del usuario (si aplica) - ✅ NUEVO
	TransactionStatus string                 `protobuf:"bytes,16,opt,name=transaction_status,json=transactionStatus,proto3" json:"transaction_status,omitempty"` // Estado de la transacción (opcional) - ✅ NUEVO
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UsedAt            *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"` // Fecha de uso (opcional)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TicketResponse) Reset() {
	*x = TicketResponse{}
	mi := &file_osmi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketResponse) ProtoMessage() {}

func (x *TicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketResponse.ProtoReflect.Descriptor instead.
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{3}
}

func (x *TicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TicketResponse) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

func (x *TicketResponse) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *TicketResponse) GetEventDate() string {
	if x != nil {
		return x.EventDate
	}
	return ""
}

func (x *TicketResponse) GetEventLocation() string {
	if x != nil {
		return x.EventLocation
	}
	return ""
}

func (x *TicketResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *TicketResponse) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *TicketResponse) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *TicketResponse) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *TicketResponse) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *TicketResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *TicketResponse) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *TicketResponse) GetTransactionStatus() string {
	if x != nil {
		return x.TransactionStatus
	}
	return ""
}

func (x *TicketResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TicketResponse) GetUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UsedAt
	}
	return nil
}

type TicketListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketResponse      `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketListResponse) Reset() {
	*x = TicketListResponse{}
	mi := &file_osmi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketListResponse) ProtoMessage() {}

func (x *TicketListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketListResponse.ProtoReflect.Descriptor instead.
func (*TicketListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{4}
}

func (x *TicketListResponse) GetTickets() []*TicketResponse {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *TicketListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ============ CUSTOMERS - ACTUALIZADOS ============
type CustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // (requerido)
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                   // (requerido)
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                                   // (opcional)
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // UUID del usuario (opcional) - ✅ NUEVA BASE DE DATOS
	CustomerType  string                 `protobuf:"bytes,5,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"` // registered, guest, corporate (default: guest) - ✅ NUEVO
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`                                 // web, app, etc. (default: web) - ✅ NUEVO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerRequest) Reset() {
	*x = CustomerRequest{}
	mi := &file_osmi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRequest) ProtoMessage() {}

func (x *CustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRequest.ProtoReflect.Descriptor instead.
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{5}
}

func (x *CustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CustomerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CustomerRequest) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *CustomerRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CustomerLookup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*CustomerLookup_PublicId
	//	*CustomerLookup_Email
	//	*CustomerLookup_Id
	Lookup        isCustomerLookup_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerLookup) Reset() {
	*x = CustomerLookup{}
	mi := &file_osmi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerLookup) ProtoMessage() {}

func (x *CustomerLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerLookup.ProtoReflect.Descriptor instead.
func (*CustomerLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{6}
}

func (x *CustomerLookup) GetLookup() isCustomerLookup_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *CustomerLookup) GetPublicId() string {
	if x != nil {
		if x, ok := x.Lookup.(*CustomerLookup_PublicId); ok {
			return x.PublicId
		}
	}
	return ""
}

func (x *CustomerLookup) GetEmail() string {
	if x != nil {
		if x, ok := x.Lookup.(*CustomerLookup_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *CustomerLookup) GetId() int32 {
	if x != nil {
		if x, ok := x.Lookup.(*CustomerLookup_Id); ok {
			return x.Id
		}
	}
	return 0
}

type isCustomerLookup_Lookup interface {
	isCustomerLookup_Lookup()
}

type CustomerLookup_PublicId struct {
	PublicId string `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3,oneof"` // UUID público del cliente
}

type CustomerLookup_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"` // Email del cliente
}

type CustomerLookup_Id struct {
	Id int32 `protobuf:"varint,3,opt,name=id,proto3,oneof"` // ID interno (para uso interno)
}

func (*CustomerLookup_PublicId) isCustomerLookup_Lookup() {}

func (*CustomerLookup_Email) isCustomerLookup_Lookup() {}

func (*CustomerLookup_Id) isCustomerLookup_Lookup() {}

type CustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CustomerType  string                 `protobuf:"bytes,5,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`     // registered, guest, corporate - ✅ NUEVA BASE DE DATOS
	LoyaltyPoints int32                  `protobuf:"varint,6,opt,name=loyalty_points,json=loyaltyPoints,proto3" json:"loyalty_points,omitempty"` // Puntos de fidelidad - ✅ NUEVO
	IsVerified    bool                   `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`          // Verificación de email - ✅ NUEVO
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`                                     // Origen del cliente - ✅ NUEVO
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerResponse) Reset() {
	*x = CustomerResponse{}
	mi := &file_osmi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerResponse) ProtoMessage() {}

func (x *CustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerResponse.ProtoReflect.Descriptor instead.
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{7}
}

func (x *CustomerResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CustomerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CustomerResponse) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *CustomerResponse) GetLoyaltyPoints() int32 {
	if x != nil {
		return x.LoyaltyPoints
	}
	return 0
}

func (x *CustomerResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *CustomerResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CustomerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CustomerResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ============ USERS ============
type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // (requerido)
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // (requerido)
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // (requerido, min: 6 caracteres)
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`         // customer, organizer, admin, guest (default: customer) - ✅ NUEVO: guest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_osmi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{8}
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID público
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`               // active, inactive
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"` // customer, organizer, admin, guest - ✅ NUEVO: guest
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ✅ NUEVO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_osmi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{9}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ============ EVENTS ============
type EventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                 // (requerido)
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                   // (opcional)
	ShortDescription string                 `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"` // (opcional)
	StartDate        string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                      // (requerido) Formato RFC3339
	EndDate          string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                            // (requerido) Formato RFC3339
	Location         string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`                                         // (requerido)
	VenueDetails     string                 `protobuf:"bytes,7,opt,name=venue_details,json=venueDetails,proto3" json:"venue_details,omitempty"`             // (opcional)
	Category         string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`                                         // (opcional)
	Tags             []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`                                                 // Lista de tags
	IsActive         bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                       // (default: true)
	IsPublished      bool                   `protobuf:"varint,11,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`              // (default: false)
	ImageUrl         string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                        // (opcional)
	BannerUrl        string                 `protobuf:"bytes,13,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`                     // (opcional)
	MaxAttendees     int32                  `protobuf:"varint,14,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`           // (opcional)
	Status           string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`                                            // draft, published, cancelled, completed, sold_out (default: draft) - ✅ NUEVO
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_osmi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{10}
}

func (x *EventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *EventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *EventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventRequest) GetVenueDetails() string {
	if x != nil {
		return x.VenueDetails
	}
	return ""
}

func (x *EventRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EventRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *EventRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EventRequest) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *EventRequest) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *EventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EventResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicId         string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	StartDate        string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Formato RFC3339
	EndDate          string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Formato RFC3339
	Location         string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	VenueDetails     string                 `protobuf:"bytes,8,opt,name=venue_details,json=venueDetails,proto3" json:"venue_details,omitempty"`
	Category         string                 `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Tags             []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	IsActive         bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPublished      bool                   `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,13,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BannerUrl        string                 `protobuf:"bytes,14,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	MaxAttendees     int32                  `protobuf:"varint,15,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`
	Status           string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"` // draft, published, cancelled, completed, sold_out - ✅ NUEVA BASE DE DATOS
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_osmi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{11}
}

func (x *EventResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *EventResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventResponse) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *EventResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *EventResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventResponse) GetVenueDetails() string {
	if x != nil {
		return x.VenueDetails
	}
	return ""
}

func (x *EventResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EventResponse) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *EventResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EventResponse) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *EventResponse) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *EventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EventResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EventLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLookup) Reset() {
	*x = EventLookup{}
	mi := &file_osmi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLookup) ProtoMessage() {}

func (x *EventLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLookup.ProtoReflect.Descriptor instead.
func (*EventLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{12}
}

func (x *EventLookup) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type EventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventResponse       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventListResponse) Reset() {
	*x = EventListResponse{}
	mi := &file_osmi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListResponse) ProtoMessage() {}

func (x *EventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventListResponse.ProtoReflect.Descriptor instead.
func (*EventListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{13}
}

func (x *EventListResponse) GetEvents() []*EventResponse {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ============ CATEGORIES ============
type CategoryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventId            string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                       // UUID del evento (requerido)
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                            // (requerido)
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                              // (opcional)
	Price              float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                                                        // (requerido, >= 0)
	QuantityAvailable  int32                  `protobuf:"varint,5,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`        // (requerido, >= 0)
	MaxTicketsPerOrder int32                  `protobuf:"varint,6,opt,name=max_tickets_per_order,json=maxTicketsPerOrder,proto3" json:"max_tickets_per_order,omitempty"` // (default: 10, min: 1)
	SalesStart         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sales_start,json=salesStart,proto3" json:"sales_start,omitempty"`                              // (default: now)
	SalesEnd           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sales_end,json=salesEnd,proto3" json:"sales_end,omitempty"`                                    // (opcional, debe ser > sales_start)
	Benefits           []string               `protobuf:"bytes,9,rep,name=benefits,proto3" json:"benefits,omitempty"`                                                    // Lista de beneficios
	IsActive           bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                                  // (default: true)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryRequest) Reset() {
	*x = CategoryRequest{}
	mi := &file_osmi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryRequest) ProtoMessage() {}

func (x *CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryRequest.ProtoReflect.Descriptor instead.
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{14}
}

func (x *CategoryRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CategoryRequest) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *CategoryRequest) GetMaxTicketsPerOrder() int32 {
	if x != nil {
		return x.MaxTicketsPerOrder
	}
	return 0
}

func (x *CategoryRequest) GetSalesStart() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesStart
	}
	return nil
}

func (x *CategoryRequest) GetSalesEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesEnd
	}
	return nil
}

func (x *CategoryRequest) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *CategoryRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CategoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PublicId           string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`                                    // UUID público
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                            // Nombre de la categoría
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                              // Descripción
	Price              float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                                                        // Precio
	QuantityAvailable  int32                  `protobuf:"varint,5,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`        // Cantidad disponible
	QuantitySold       int32                  `protobuf:"varint,6,opt,name=quantity_sold,json=quantitySold,proto3" json:"quantity_sold,omitempty"`                       // Cantidad vendida
	MaxTicketsPerOrder int32                  `protobuf:"varint,7,opt,name=max_tickets_per_order,json=maxTicketsPerOrder,proto3" json:"max_tickets_per_order,omitempty"` // Máximo por orden
	SalesStart         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sales_start,json=salesStart,proto3" json:"sales_start,omitempty"`
	SalesEnd           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sales_end,json=salesEnd,proto3" json:"sales_end,omitempty"`
	Benefits           []string               `protobuf:"bytes,10,rep,name=benefits,proto3" json:"benefits,omitempty"`                  // Beneficios
	IsActive           bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // Estado activo
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_osmi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{15}
}

func (x *CategoryResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CategoryResponse) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *CategoryResponse) GetQuantitySold() int32 {
	if x != nil {
		return x.QuantitySold
	}
	return 0
}

func (x *CategoryResponse) GetMaxTicketsPerOrder() int32 {
	if x != nil {
		return x.MaxTicketsPerOrder
	}
	return 0
}

func (x *CategoryResponse) GetSalesStart() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesStart
	}
	return nil
}

func (x *CategoryResponse) GetSalesEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesEnd
	}
	return nil
}

func (x *CategoryResponse) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *CategoryResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CategoryResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CategoryResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryResponse    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventPublicId string                 `protobuf:"bytes,3,opt,name=event_public_id,json=eventPublicId,proto3" json:"event_public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_osmi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{16}
}

func (x *CategoryListResponse) GetCategories() []*CategoryResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CategoryListResponse) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CategoryListResponse) GetEventPublicId() string {
	if x != nil {
		return x.EventPublicId
	}
	return ""
}

// ============ HEALTH CHECK ============
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // healthy, unhealthy
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_osmi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{17}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ============ COMMON ============
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_osmi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{18}
}

var File_osmi_proto protoreflect.FileDescriptor

const file_osmi_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"osmi.proto\x12\x04osmi\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x01\n" +
	"\rTicketRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"\x8b\x01\n" +
	"\fTicketLookup\x12\x1d\n" +
	"\tticket_id\x18\x01 \x01(\tH\x00R\bticketId\x12\x19\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x12!\n" +
	"\vcustomer_id\x18\x03 \x01(\tH\x00R\n" +
	"customerId\x12\x14\n" +
	"\x04code\x18\x04 \x01(\tH\x00R\x04codeB\b\n" +
	"\x06lookup\"P\n" +
	"\x19UpdateTicketStatusRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x84\x05\n" +
	"\x0eTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1e\n" +
	"\vqr_code_url\x18\x04 \x01(\tR\tqrCodeUrl\x12\x1d\n" +
	"\n" +
	"event_name\x18\x05 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"event_date\x18\x06 \x01(\tR\teventDate\x12%\n" +
	"\x0eevent_location\x18\a \x01(\tR\reventLocation\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12#\n" +
	"\rcategory_name\x18\t \x01(\tR\fcategoryName\x12\x1f\n" +
	"\vseat_number\x18\n" +
	" \x01(\tR\n" +
	"seatNumber\x12#\n" +
	"\rcustomer_name\x18\v \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\f \x01(\tR\rcustomerEmail\x12#\n" +
	"\rcustomer_type\x18\r \x01(\tR\fcustomerType\x12\x1b\n" +
	"\tuser_name\x18\x0e \x01(\tR\buserName\x12\x1b\n" +
	"\tuser_role\x18\x0f \x01(\tR\buserRole\x12-\n" +
	"\x12transaction_status\x18\x10 \x01(\tR\x11transactionStatus\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\aused_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x06usedAt\"e\n" +
	"\x12TicketListResponse\x12.\n" +
	"\atickets\x18\x01 \x03(\v2\x14.osmi.TicketResponseR\atickets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa7\x01\n" +
	"\x0fCustomerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12#\n" +
	"\rcustomer_type\x18\x05 \x01(\tR\fcustomerType\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"c\n" +
	"\x0eCustomerLookup\x12\x1d\n" +
	"\tpublic_id\x18\x01 \x01(\tH\x00R\bpublicId\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x10\n" +
	"\x02id\x18\x03 \x01(\x05H\x00R\x02idB\b\n" +
	"\x06lookup\"\xea\x02\n" +
	"\x10CustomerResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12#\n" +
	"\rcustomer_type\x18\x05 \x01(\tR\fcustomerType\x12%\n" +
	"\x0eloyalty_points\x18\x06 \x01(\x05R\rloyaltyPoints\x12\x1f\n" +
	"\vis_verified\x18\a \x01(\bR\n" +
	"isVerified\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"g\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\xf3\x01\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd5\x03\n" +
	"\fEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12#\n" +
	"\rvenue_details\x18\a \x01(\tR\fvenueDetails\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12!\n" +
	"\fis_published\x18\v \x01(\bR\visPublished\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\r \x01(\tR\tbannerUrl\x12#\n" +
	"\rmax_attendees\x18\x0e \x01(\x05R\fmaxAttendees\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\"\xe9\x04\n" +
	"\rEventResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x04 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12#\n" +
	"\rvenue_details\x18\b \x01(\tR\fvenueDetails\x12\x1a\n" +
	"\bcategory\x18\t \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12!\n" +
	"\fis_published\x18\f \x01(\bR\visPublished\x12\x1b\n" +
	"\timage_url\x18\r \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x0e \x01(\tR\tbannerUrl\x12#\n" +
	"\rmax_attendees\x18\x0f \x01(\x05R\fmaxAttendees\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\vEventLookup\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"a\n" +
	"\x11EventListResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.osmi.EventResponseR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x89\x03\n" +
	"\x0fCategoryRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12-\n" +
	"\x12quantity_available\x18\x05 \x01(\x05R\x11quantityAvailable\x121\n" +
	"\x15max_tickets_per_order\x18\x06 \x01(\x05R\x12maxTicketsPerOrder\x12;\n" +
	"\vsales_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"salesStart\x127\n" +
	"\tsales_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bsalesEnd\x12\x1a\n" +
	"\bbenefits\x18\t \x03(\tR\bbenefits\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"\xa7\x04\n" +
	"\x10CategoryResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12-\n" +
	"\x12quantity_available\x18\x05 \x01(\x05R\x11quantityAvailable\x12#\n" +
	"\rquantity_sold\x18\x06 \x01(\x05R\fquantitySold\x121\n" +
	"\x15max_tickets_per_order\x18\a \x01(\x05R\x12maxTicketsPerOrder\x12;\n" +
	"\vsales_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"salesStart\x127\n" +
	"\tsales_end\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bsalesEnd\x12\x1a\n" +
	"\bbenefits\x18\n" +
	" \x03(\tR\bbenefits\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x95\x01\n" +
	"\x14CategoryListResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.osmi.CategoryResponseR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12&\n" +
	"\x0fevent_public_id\x18\x03 \x01(\tR\reventPublicId\"\x96\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\a\n" +
	"\x05Empty2\x89\t\n" +
	"\vOsmiService\x12Q\n" +
	"\fCreateTicket\x12\x13.osmi.TicketRequest\x1a\x14.osmi.TicketResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/tickets\x12P\n" +
	"\vListTickets\x12\x12.osmi.TicketLookup\x1a\x18.osmi.TicketListResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/tickets\x12]\n" +
	"\x10GetTicketDetails\x12\x12.osmi.TicketLookup\x1a\x14.osmi.TicketResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/tickets/{ticket_id}\x12v\n" +
	"\x12UpdateTicketStatus\x12\x1f.osmi.UpdateTicketStatusRequest\x1a\x14.osmi.TicketResponse\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/v1/tickets/{ticket_id}/status\x12Y\n" +
	"\x0eCreateCustomer\x12\x15.osmi.CustomerRequest\x1a\x16.osmi.CustomerResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/customers\x12^\n" +
	"\vGetCustomer\x12\x14.osmi.CustomerLookup\x1a\x16.osmi.CustomerResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/customers/{public_id}\x12I\n" +
	"\n" +
	"CreateUser\x12\x11.osmi.UserRequest\x1a\x12.osmi.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12M\n" +
	"\vCreateEvent\x12\x12.osmi.EventRequest\x1a\x13.osmi.EventResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/events\x12R\n" +
	"\bGetEvent\x12\x11.osmi.EventLookup\x1a\x13.osmi.EventResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/events/{public_id}\x12F\n" +
	"\n" +
	"ListEvents\x12\v.osmi.Empty\x1a\x17.osmi.EventListResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/events\x12Z\n" +
	"\x0eCreateCategory\x12\x15.osmi.CategoryRequest\x1a\x16.osmi.CategoryResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/categories\x12n\n" +
	"\x12GetEventCategories\x12\x11.osmi.EventLookup\x1a\x1a.osmi.CategoryListResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/events/{public_id}/categories\x12A\n" +
	"\vHealthCheck\x12\v.osmi.Empty\x1a\x14.osmi.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthB7Z5github.com/franciscozamorau/osmi-protobuf/gen/pb;osmib\x06proto3"

var (
	file_osmi_proto_rawDescOnce sync.Once
	file_osmi_proto_rawDescData []byte
)

func file_osmi_proto_rawDescGZIP() []byte {
	file_osmi_proto_rawDescOnce.Do(func() {
		file_osmi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osmi_proto_rawDesc), len(file_osmi_proto_rawDesc)))
	})
	return file_osmi_proto_rawDescData
}

var file_osmi_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_osmi_proto_goTypes = []any{
	(*TicketRequest)(nil),             // 0: osmi.TicketRequest
	(*TicketLookup)(nil),              // 1: osmi.TicketLookup
	(*UpdateTicketStatusRequest)(nil), // 2: osmi.UpdateTicketStatusRequest
	(*TicketResponse)(nil),            // 3: osmi.TicketResponse
	(*TicketListResponse)(nil),        // 4: osmi.TicketListResponse
	(*CustomerRequest)(nil),           // 5: osmi.CustomerRequest
	(*CustomerLookup)(nil),            // 6: osmi.CustomerLookup
	(*CustomerResponse)(nil),          // 7: osmi.CustomerResponse
	(*UserRequest)(nil),               // 8: osmi.UserRequest
	(*UserResponse)(nil),              // 9: osmi.UserResponse
	(*EventRequest)(nil),              // 10: osmi.EventRequest
	(*EventResponse)(nil),             // 11: osmi.EventResponse
	(*EventLookup)(nil),               // 12: osmi.EventLookup
	(*EventListResponse)(nil),         // 13: osmi.EventListResponse
	(*CategoryRequest)(nil),           // 14: osmi.CategoryRequest
	(*CategoryResponse)(nil),          // 15: osmi.CategoryResponse
	(*CategoryListResponse)(nil),      // 16: osmi.CategoryListResponse
	(*HealthResponse)(nil),            // 17: osmi.HealthResponse
	(*Empty)(nil),                     // 18: osmi.Empty
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
}
var file_osmi_proto_depIdxs = []int32{
	19, // 0: osmi.TicketResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: osmi.TicketResponse.used_at:type_name -> google.protobuf.Timestamp
	3,  // 2: osmi.TicketListResponse.tickets:type_name -> osmi.TicketResponse
	19, // 3: osmi.CustomerResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 4: osmi.CustomerResponse.updated_at:type_name -> google.protobuf.Timestamp
	19, // 5: osmi.UserResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 6: osmi.UserResponse.updated_at:type_name -> google.protobuf.Timestamp
	19, // 7: osmi.EventResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 8: osmi.EventResponse.updated_at:type_name -> google.protobuf.Timestamp
	11, // 9: osmi.EventListResponse.events:type_name -> osmi.EventResponse
	19, // 10: osmi.CategoryRequest.sales_start:type_name -> google.protobuf.Timestamp
	19, // 11: osmi.CategoryRequest.sales_end:type_name -> google.protobuf.Timestamp
	19, // 12: osmi.CategoryResponse.sales_start:type_name -> google.protobuf.Timestamp
	19, // 13: osmi.CategoryResponse.sales_end:type_name -> google.protobuf.Timestamp
	19, // 14: osmi.CategoryResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 15: osmi.CategoryResponse.updated_at:type_name -> google.protobuf.Timestamp
	15, // 16: osmi.CategoryListResponse.categories:type_name -> osmi.CategoryResponse
	19, // 17: osmi.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 18: osmi.OsmiService.CreateTicket:input_type -> osmi.TicketRequest
	1,  // 19: osmi.OsmiService.ListTickets:input_type -> osmi.TicketLookup
	1,  // 20: osmi.OsmiService.GetTicketDetails:input_type -> osmi.TicketLookup
	2,  // 21: osmi.OsmiService.UpdateTicketStatus:input_type -> osmi.UpdateTicketStatusRequest
	5,  // 22: osmi.OsmiService.CreateCustomer:input_type -> osmi.CustomerRequest
	6,  // 23: osmi.OsmiService.GetCustomer:input_type -> osmi.CustomerLookup
	8,  // 24: osmi.OsmiService.CreateUser:input_type -> osmi.UserRequest
	10, // 25: osmi.OsmiService.CreateEvent:input_type -> osmi.EventRequest
	12, // 26: osmi.OsmiService.GetEvent:input_type -> osmi.EventLookup
	18, // 27: osmi.OsmiService.ListEvents:input_type -> osmi.Empty
	14, // 28: osmi.OsmiService.CreateCategory:input_type -> osmi.CategoryRequest
	12, // 29: osmi.OsmiService.GetEventCategories:input_type -> osmi.EventLookup
	18, // 30: osmi.OsmiService.HealthCheck:input_type -> osmi.Empty
	3,  // 31: osmi.OsmiService.CreateTicket:output_type -> osmi.TicketResponse
	4,  // 32: osmi.OsmiService.ListTickets:output_type -> osmi.TicketListResponse
	3,  // 33: osmi.OsmiService.GetTicketDetails:output_type -> osmi.TicketResponse
	3,  // 34: osmi.OsmiService.UpdateTicketStatus:output_type -> osmi.TicketResponse
	7,  // 35: osmi.OsmiService.CreateCustomer:output_type -> osmi.CustomerResponse
	7,  // 36: osmi.OsmiService.GetCustomer:output_type -> osmi.CustomerResponse
	9,  // 37: osmi.OsmiService.CreateUser:output_type -> osmi.UserResponse
	11, // 38: osmi.OsmiService.CreateEvent:output_type -> osmi.EventResponse
	11, // 39: osmi.OsmiService.GetEvent:output_type -> osmi.EventResponse
	13, // 40: osmi.OsmiService.ListEvents:output_type -> osmi.EventListResponse
	15, // 41: osmi.OsmiService.CreateCategory:output_type -> osmi.CategoryResponse
	16, // 42: osmi.OsmiService.GetEventCategories:output_type -> osmi.CategoryListResponse
	17, // 43: osmi.OsmiService.HealthCheck:output_type -> osmi.HealthResponse
	31, // [31:44] is the sub-list for method output_type
	18, // [18:31] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_osmi_proto_init() }
func file_osmi_proto_init() {
	if File_osmi_proto != nil {
		return
	}
	file_osmi_proto_msgTypes[1].OneofWrappers = []any{
		(*TicketLookup_TicketId)(nil),
		(*TicketLookup_UserId)(nil),
		(*TicketLookup_CustomerId)(nil),
		(*TicketLookup_Code)(nil),
	}
	file_osmi_proto_msgTypes[6].OneofWrappers = []any{
		(*CustomerLookup_PublicId)(nil),
		(*CustomerLookup_Email)(nil),
		(*CustomerLookup_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osmi_proto_rawDesc), len(file_osmi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osmi_proto_goTypes,
		DependencyIndexes: file_osmi_proto_depIdxs,
		MessageInfos:      file_osmi_proto_msgTypes,
	}.Build()
	File_osmi_proto = out.File
	file_osmi_proto_goTypes = nil
	file_osmi_proto_depIdxs = nil
}
